/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package posant.mainapp.Employee_frames;

import posant.databases.db;
import posant.mainapp.*;

public class EmployeeProfile extends javax.swing.JFrame {
    protected String username;
    protected String password;
    db database ;
    String dbname;
    myDate date;
    int id;
    public EmployeeProfile(String db,String username, String password, int id) {
        dbname = db;
        this.id = id;
        database = new db(dbname , username, password);
        this.username = username;
        this.password = password;
        date = new myDate();
        initComponents();
        set_values(id);
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        employeeprofilenamefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        employeeprofilephonefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        employeeprofilesalaryfield = new javax.swing.JTextField();
        employeeprofilejobcombo = new javax.swing.JComboBox<>();
        employeeprofiletypecombo = new javax.swing.JComboBox<>();
        addemployeeerrorlabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emyloyeeprofilebrithdateyearcombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emyloyeeprofilebrithdatemonthcombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        emyloyeeprofilebrithdatedaycombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        emyloyeeprofilestartdateyearcombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emyloyeeprofilestartdatemonthcombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        emyloyeeprofilestartdatedaycombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        employeeprofileerrorlabel = new javax.swing.JLabel();
        employeeprofilereasoncombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        deleteemployeebutton = new javax.swing.JButton();
        updateemployeebutton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE
        );
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile");

        employeeprofilenamefield.setBackground(new java.awt.Color(0, 153, 153));
        employeeprofilenamefield.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        employeeprofilenamefield.setForeground(new java.awt.Color(255, 255, 255));
        employeeprofilenamefield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        employeeprofilenamefield.setOpaque(false);
        employeeprofilenamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeprofilenamefieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");

        employeeprofilephonefield.setBackground(new java.awt.Color(0, 153, 153));
        employeeprofilephonefield.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        employeeprofilephonefield.setForeground(new java.awt.Color(255, 255, 255));
        employeeprofilephonefield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        employeeprofilephonefield.setOpaque(false);
        employeeprofilephonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeprofilephonefieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phone");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Salary");

        employeeprofilesalaryfield.setBackground(new java.awt.Color(0, 153, 153));
        employeeprofilesalaryfield.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        employeeprofilesalaryfield.setForeground(new java.awt.Color(255, 255, 255));
        employeeprofilesalaryfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        employeeprofilesalaryfield.setOpaque(false);

        addemployeeerrorlabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        addemployeeerrorlabel.setForeground(new java.awt.Color(255, 0, 51));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Birth Date");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("year:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("month:");

        emyloyeeprofilebrithdatemonthcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emyloyeeprofilebrithdatemonthcomboActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("day:");

        emyloyeeprofilebrithdatedaycombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emyloyeeprofilebrithdatedaycomboActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("year:");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Start Date");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("month:");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("day:");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Type:");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Job:");

        employeeprofileerrorlabel.setForeground(new java.awt.Color(255, 0, 51));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reason:");

        deleteemployeebutton.setBackground(new java.awt.Color(255, 255, 255));
        deleteemployeebutton.setForeground(new java.awt.Color(51, 51, 51));
        deleteemployeebutton.setText("Delete");
        deleteemployeebutton.setBorder(null);
        deleteemployeebutton.setFocusPainted(false);
        deleteemployeebutton.setFocusable(false);
        deleteemployeebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteemployeebuttonMouseClicked(evt);
            }
        });
        deleteemployeebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteemployeebuttonActionPerformed(evt);
            }
        });

        updateemployeebutton1.setBackground(new java.awt.Color(255, 255, 255));
        updateemployeebutton1.setForeground(new java.awt.Color(51, 51, 51));
        updateemployeebutton1.setText("Update");
        updateemployeebutton1.setBorder(null);
        updateemployeebutton1.setFocusPainted(false);
        updateemployeebutton1.setFocusable(false);
        updateemployeebutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateemployeebutton1MouseClicked(evt);
            }
        });
        updateemployeebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateemployeebutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addemployeeerrorlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeprofilephonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(employeeprofilesalaryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeprofilenamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emyloyeeprofilebrithdateyearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emyloyeeprofilebrithdatemonthcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emyloyeeprofilebrithdatedaycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeprofileerrorlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(emyloyeeprofilestartdateyearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel12))
                                    .addComponent(employeeprofilejobcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(emyloyeeprofilestartdatemonthcombo, 0, 100, Short.MAX_VALUE)
                                            .addComponent(employeeprofilereasoncombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeprofiletypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emyloyeeprofilestartdatedaycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteemployeebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(updateemployeebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(employeeprofilenamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(employeeprofilephonefield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeprofilesalaryfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emyloyeeprofilebrithdateyearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(emyloyeeprofilebrithdatemonthcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(emyloyeeprofilebrithdatedaycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emyloyeeprofilestartdateyearcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(emyloyeeprofilestartdatemonthcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(emyloyeeprofilestartdatedaycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeprofilereasoncombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(employeeprofiletypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(employeeprofilejobcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeeprofileerrorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(deleteemployeebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)))
                .addComponent(addemployeeerrorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(565, Short.MAX_VALUE)
                    .addComponent(updateemployeebutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(114, 114, 114)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emyloyeeprofilebrithdatemonthcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emyloyeeprofilebrithdatemonthcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emyloyeeprofilebrithdatemonthcomboActionPerformed

    
    private void emyloyeeprofilebrithdatedaycomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emyloyeeprofilebrithdatedaycomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emyloyeeprofilebrithdatedaycomboActionPerformed

    private void employeeprofilenamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeprofilenamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeprofilenamefieldActionPerformed

    private void employeeprofilephonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeprofilephonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeprofilephonefieldActionPerformed

    private void deleteemployeebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteemployeebuttonMouseClicked
        int reason_id = employeeprofilereasoncombo.getSelectedIndex()+1;
        database.add_archive(id,reason_id);
        dispose();
    }//GEN-LAST:event_deleteemployeebuttonMouseClicked

    private void deleteemployeebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteemployeebuttonActionPerformed
        
    }//GEN-LAST:event_deleteemployeebuttonActionPerformed

    private void updateemployeebutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateemployeebutton1MouseClicked
        String new_name = employeeprofilenamefield.getText();
        String new_phone = employeeprofilephonefield.getText();
        Double new_salary = Double.parseDouble(employeeprofilesalaryfield.getText());
        
        int job_id = employeeprofilejobcombo.getSelectedIndex()+1;
        int type_id = employeeprofiletypecombo.getSelectedIndex()+1;
        String new_birth_date = date.form_date(Integer.parseInt((String) emyloyeeprofilebrithdateyearcombo.getSelectedItem()), Integer.parseInt((String) emyloyeeprofilebrithdatemonthcombo.getSelectedItem()), Integer.parseInt((String) emyloyeeprofilebrithdatedaycombo.getSelectedItem()));
        String new_start_date = date.form_date(Integer.parseInt((String) emyloyeeprofilestartdateyearcombo.getSelectedItem()), Integer.parseInt((String) emyloyeeprofilestartdatemonthcombo.getSelectedItem()), Integer.parseInt((String) emyloyeeprofilestartdatedaycombo.getSelectedItem()));
        
            
            database.update_work(id, new_start_date, job_id);
            database.update_salary(new_salary, type_id, id);
            database.update_employee(new_name, id, new_phone, new_birth_date);
            dispose();
    }//GEN-LAST:event_updateemployeebutton1MouseClicked

    private void updateemployeebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateemployeebutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateemployeebutton1ActionPerformed

    private void set_values(int id){
       second_ini();
      employeeprofilenamefield.setText(database.get_employee_with_id(id)[1]);
      employeeprofilephonefield.setText(database.get_employee_with_id(id)[2]);
      employeeprofilesalaryfield.setText(database.get_employee_with_id(id)[7]);
      emyloyeeprofilebrithdateyearcombo.setSelectedItem(database.get_employee_with_id(id)[3].substring(0, 4));
      emyloyeeprofilebrithdatemonthcombo.setSelectedItem(database.get_employee_with_id(id)[3].substring(5, 7));
      emyloyeeprofilebrithdatedaycombo.setSelectedItem(database.get_employee_with_id(id)[3].substring(8));

      emyloyeeprofilestartdateyearcombo.setSelectedItem(database.get_employee_with_id(id)[4].substring(0, 4));
      emyloyeeprofilestartdatemonthcombo.setSelectedItem(database.get_employee_with_id(id)[4].substring(5, 7));
      emyloyeeprofilestartdatedaycombo.setSelectedItem(database.get_employee_with_id(id)[4].substring(8));
      employeeprofilejobcombo.setSelectedItem(database.get_employee_with_id(id)[6]);
      employeeprofiletypecombo.setSelectedItem(database.get_employee_with_id(id)[5]);

    }
    
    private void second_ini(){
        database.select_lookup(employeeprofilejobcombo,"job_lookup");
        database.select_lookup(employeeprofiletypecombo, "type_lookup");
        database.select_lookup(employeeprofilereasoncombo, "Reasons_lookup");
        date.display_all(emyloyeeprofilebrithdateyearcombo, emyloyeeprofilebrithdatemonthcombo, emyloyeeprofilebrithdatedaycombo);
        date.display_all(emyloyeeprofilestartdateyearcombo, emyloyeeprofilestartdatemonthcombo, emyloyeeprofilestartdatedaycombo);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addemployeeerrorlabel;
    private javax.swing.JButton deleteemployeebutton;
    private javax.swing.JLabel employeeprofileerrorlabel;
    private javax.swing.JComboBox<String> employeeprofilejobcombo;
    private javax.swing.JTextField employeeprofilenamefield;
    private javax.swing.JTextField employeeprofilephonefield;
    private javax.swing.JComboBox<String> employeeprofilereasoncombo;
    private javax.swing.JTextField employeeprofilesalaryfield;
    private javax.swing.JComboBox<String> employeeprofiletypecombo;
    private javax.swing.JComboBox<String> emyloyeeprofilebrithdatedaycombo;
    private javax.swing.JComboBox<String> emyloyeeprofilebrithdatemonthcombo;
    private javax.swing.JComboBox<String> emyloyeeprofilebrithdateyearcombo;
    private javax.swing.JComboBox<String> emyloyeeprofilestartdatedaycombo;
    private javax.swing.JComboBox<String> emyloyeeprofilestartdatemonthcombo;
    private javax.swing.JComboBox<String> emyloyeeprofilestartdateyearcombo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updateemployeebutton1;
    // End of variables declaration//GEN-END:variables
}
